name: Run Unit Tests

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      shell: bash
      run: npm install
    - name: Run unit tests
      shell: bash
      run: npm run test
