name: Run unit tests in all branches except main

on:
  push:
    branches:
      - 'yisus44/refactor/testing'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Run units tests
        uses: ./.github/workflows/run-unit-tests
